#!/usr/bin/env bash
# detach-manager.sh - Background/detached execution for Tarvos sessions

# ──────────────────────────────────────────────────────────────
# detach_get_pid
# Read the PID from the session's pid file.
# Args: $1 = session_name
# Outputs: PID (integer) or nothing
# Returns 0 if pid file exists, 1 otherwise
# ──────────────────────────────────────────────────────────────
detach_get_pid() {
    local name="$1"
    local pid_file
    pid_file="${SESSIONS_DIR}/${name}/pid"

    if [[ ! -f "$pid_file" ]]; then
        return 1
    fi

    local pid
    pid=$(cat "$pid_file" 2>/dev/null)
    if [[ -z "$pid" ]]; then
        return 1
    fi

    echo "$pid"
    return 0
}

# ──────────────────────────────────────────────────────────────
# detach_is_running
# Check if the detached session process is actually alive.
# Args: $1 = session_name
# Returns 0 if running, 1 if not.
# Side effect: if PID file exists but process is dead, removes
# the stale pid file and updates session status to "stopped".
# ──────────────────────────────────────────────────────────────
detach_is_running() {
    local name="$1"
    local pid_file
    pid_file="${SESSIONS_DIR}/${name}/pid"

    local pid
    if ! pid=$(detach_get_pid "$name"); then
        return 1
    fi

    if kill -0 "$pid" 2>/dev/null; then
        return 0
    fi

    # Process is dead but pid file is stale — clean up
    rm -f "$pid_file"
    if declare -f session_set_status &>/dev/null; then
        session_set_status "$name" "stopped" 2>/dev/null || true
    fi
    return 1
}

# ──────────────────────────────────────────────────────────────
# detach_stop
# Send SIGTERM to the detached session process; escalate to
# SIGKILL after 2 seconds if still alive.
# Args: $1 = session_name
# Returns 0 on success, 1 if nothing to stop.
# ──────────────────────────────────────────────────────────────
detach_stop() {
    local name="$1"
    local pid_file
    pid_file="${SESSIONS_DIR}/${name}/pid"

    local pid
    if ! pid=$(detach_get_pid "$name"); then
        return 1
    fi

    if ! kill -0 "$pid" 2>/dev/null; then
        rm -f "$pid_file"
        return 1
    fi

    # SIGTERM first
    kill -TERM "$pid" 2>/dev/null || true

    # Wait up to 2 seconds
    local waited=0
    while kill -0 "$pid" 2>/dev/null && (( waited < 20 )); do
        sleep 0.1
        (( waited++ ))
    done

    # SIGKILL if still alive
    if kill -0 "$pid" 2>/dev/null; then
        kill -KILL "$pid" 2>/dev/null || true
        sleep 0.2
    fi

    rm -f "$pid_file"

    # Update session status
    if declare -f session_set_status &>/dev/null; then
        session_set_status "$name" "stopped" 2>/dev/null || true
    fi

    return 0
}

# ──────────────────────────────────────────────────────────────
# detach_start
# Start a session in the background via nohup.
# Writes a wrapper script to the session folder, runs it via
# nohup, and saves the PID to <session>/pid.
# Args:
#   $1 = session_name
#   $2 = tarvos_script_path (absolute path to tarvos.sh)
#   $3 = project_dir        (absolute path to project directory)
#   $4 = tarvos_command     (optional; default: "begin"; use "continue" for resumed sessions)
# Returns 0 on success, 1 on failure.
# ──────────────────────────────────────────────────────────────
detach_start() {
    local name="$1"
    local tarvos_script="$2"
    local project_dir="$3"
    local tarvos_command="${4:-begin}"

    local session_folder
    session_folder="${SESSIONS_DIR}/${name}"
    local output_log="${session_folder}/output.log"
    local pid_file="${session_folder}/pid"
    local wrapper_script="${session_folder}/run.sh"

    if [[ ! -d "$session_folder" ]]; then
        echo "tarvos: session folder not found: ${session_folder}" >&2
        return 1
    fi

    # Build the wrapper script that tarvos will execute in the background.
    # It cd's to the project dir, then invokes `tarvos <command> <name>`.
    cat > "$wrapper_script" <<WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated by tarvos detach_start — do not edit
cd "${project_dir}" || exit 1
exec "${tarvos_script}" ${tarvos_command} "${name}"
WRAPPER_EOF
    chmod +x "$wrapper_script"

    # Launch via nohup, redirect stdout+stderr to output.log
    nohup "$wrapper_script" >> "$output_log" 2>&1 &
    local bg_pid=$!

    # Save PID
    echo "$bg_pid" > "$pid_file"

    echo "Session '${name}' started in background (PID: ${bg_pid})"
    echo "  Log:    ${output_log}"
    echo "  TUI:    tarvos tui"
    echo "  Attach: tarvos attach ${name}"

    return 0
}

# ──────────────────────────────────────────────────────────────
# detach_attach
# Tail the session's output.log, streaming live output.
# Ctrl+C sends SIGINT to this (the attaching) shell only —
# the background session continues running.
# Args: $1 = session_name
# Returns when the user hits Ctrl+C (or log is gone).
# ──────────────────────────────────────────────────────────────
detach_attach() {
    local name="$1"

    local session_folder
    session_folder="${SESSIONS_DIR}/${name}"
    local output_log="${session_folder}/output.log"
    local pid_file="${session_folder}/pid"

    if [[ ! -d "$session_folder" ]]; then
        echo "tarvos: session '${name}' not found." >&2
        return 1
    fi

    if [[ ! -f "$output_log" ]]; then
        echo "tarvos: no output log found for session '${name}'." >&2
        echo "  The session may not have been started in background mode." >&2
        return 1
    fi

    # Check if process is still alive
    local pid
    pid=$(cat "$pid_file" 2>/dev/null || true)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
        echo "Attached to session '${name}' (PID: ${pid}). Press Ctrl+C to detach (session continues in background)."
    else
        echo "Session '${name}' is no longer running. Showing log output:"
    fi

    echo "──────────────────────────────────────────────────────────"

    # Set up a trap so Ctrl+C only interrupts the tail, not the bg session
    local tail_pid
    tail -f "$output_log" &
    tail_pid=$!

    # Restore SIGINT default so Ctrl+C kills only the tail process
    trap "kill $tail_pid 2>/dev/null; echo ''; echo 'Detached. Session continues in background.'; return 0" INT

    wait "$tail_pid" 2>/dev/null || true

    # Reset trap
    trap - INT

    return 0
}
