#!/usr/bin/env bash
# prompt-builder.sh - Builds composite prompts for each Tarvos iteration

# Build the main prompt for an iteration
# Args: $1 = PRD file path, $2 = protocol file path, $3 = project directory, $4 = progress file (optional, overrides default)
# Outputs the composite prompt to stdout
build_prompt() {
    local prd_file="$1"
    local protocol_file="$2"
    local project_dir="$3"
    # Allow explicit progress file override (for session-based runs)
    local progress_file="${4:-${project_dir}/progress.md}"

    local prompt=""

    # Section 1: Master Plan (PRD)
    prompt+="# Master Plan (PRD)"$'\n'
    prompt+=$'\n'
    prompt+="$(cat "$prd_file")"$'\n'
    prompt+=$'\n'

    # Section 2: Tarvos Protocol (strip YAML frontmatter from SKILL.md)
    prompt+="# Tarvos Protocol"$'\n'
    prompt+=$'\n'
    prompt+="$(awk '/^---/{i++; if(i==2) found=1; next} found' "$protocol_file")"$'\n'
    prompt+=$'\n'

    # Section 3: Previous Agent's Progress Report (if exists)
    if [[ -f "$progress_file" ]]; then
        prompt+="# Previous Agent's Progress Report"$'\n'
        prompt+=$'\n'
        prompt+="$(cat "$progress_file")"$'\n'
        prompt+=$'\n'
        prompt+="## Your Task"$'\n'
        prompt+=$'\n'
        prompt+="Continue from where the previous agent left off. Read the progress report above carefully to understand what has been completed and what remains. Focus on the current phase or the next phase as appropriate."$'\n'
    else
        prompt+="## Your Task"$'\n'
        prompt+=$'\n'
        prompt+="This is the first iteration. Begin with Phase 1 of the PRD. Read the full plan above, then start implementing Phase 1."$'\n'
    fi

    echo "$prompt"
}

# Build the context-limit continuation prompt
# Sent via `claude -c -p` when context limit is reached
# Args: $1 = progress file path (optional; defaults to "progress.md" in the project root)
# Outputs the prompt to stdout
build_context_limit_prompt() {
    local progress_file="${1:-progress.md}"
    cat <<PROMPT
CONTEXT LIMIT REACHED. You must stop development immediately.

1. Write a progress report to: ${progress_file}
KEEP IT UNDER 40 LINES. Use this format:

\`\`\`markdown
# Progress Report

## Current Status
Phase [N] of [Total]: [Phase Title]
Status: IN_PROGRESS

## What Was Done This Session
- [file]: [brief description of change]

## Immediate Next Task
[1-2 sentences: what should the next agent do first]

## Key Files for Next Task
- [Only 2-3 files the next agent needs to touch]

## Gotchas
- [Only non-obvious blockers — skip section if none]
\`\`\`

Do NOT include: line numbers, function signatures, code snippets, design docs, architecture notes, full file listings, or anything already in the PRD. The next agent can read the code itself. Be a sticky note, not a design document.

2. After writing the progress report, output on its own line:

PHASE_IN_PROGRESS

Do NOT continue any other development work. Write the progress report and stop.
PROMPT
}

# Build the recovery prompt when progress.md is missing
# Args: $1 = project directory, $2 = progress file path (optional, defaults to project_dir/progress.md)
# Outputs the prompt to stdout
build_recovery_prompt() {
    local project_dir="$1"
    local progress_file="${2:-${project_dir}/progress.md}"

    cat <<PROMPT
You are a recovery agent for the Tarvos orchestration system. The previous agent completed work but failed to write a progress.md file.

Examine the current state of the project in "${project_dir}":
- Check git log for recent commits
- Look at what files exist and their state
- Determine what phase of work was being done

Then write a progress.md file at: ${progress_file}
KEEP IT UNDER 40 LINES. Use this format:

\`\`\`markdown
# Progress Report

## Current Status
Phase [N] of [Total]: [Phase Title]
Status: IN_PROGRESS

## What Was Done This Session
- [file]: [brief description of change]

## Immediate Next Task
[1-2 sentences: what should the next agent do first]

## Key Files for Next Task
- [Only 2-3 files the next agent needs to touch]

## Gotchas
- [Only non-obvious blockers — skip if none]
- NOTE: This progress report was auto-generated by a recovery agent. Verify accuracy.
\`\`\`

Do NOT include: line numbers, function signatures, code snippets, design docs, or full file listings.

After writing progress.md, output on its own line:

PHASE_IN_PROGRESS
PROMPT
}
